services:
  react-app:
    build:
      context: ./web_test
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    env_file:
      - ./web_test/.env
    environment:
      - REACT_APP_BASE_URL=http://localhost:5159
    restart: unless-stopped
